domain:
  live: "rewards.sky.com"

# Type the name of the directory that shots will be stored in
directory:
  baseline: 'public/screenshots_baseline'
  current: 'public/screenshots_current'


screen_widths:
  - 320
  - 600
#  - 768
#  - 1024
#  - 1280

browsers:
#  - chrome
  - firefox

paths:
  home: /home
#  sky_o2: /home/sky-at-the-o2
#  my_photos: /home/sky-at-the-o2/myphotos
#  sky_live_comp: /home/sky-at-the-o2/myphotos/comp