domain:
  google_uk: "www.google.co.uk"

# Type the name of the directory that shots will be stored in
directory:
  baseline: 'public/screenshots_baseline'
  current: 'public/screenshots_current'


screen_widths:
  - 320
  - 600

browsers:
  - firefox

paths:
  home: /
